name: Deploy Backend to Docker Hub

on:
  push:
    branches:
      - master  # Ejecuta el workflow cuando hay un push a la rama "master"
      - dev     # Ejecuta el workflow cuando hay un push a la rama "dev"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production  # Define el entorno de producción

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Obtener nombre de la rama
        id: branch_name
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "🔖 Rama detectada: ${GITHUB_REF#refs/heads/}"

      - name: Define Image Tag
        run: |
          echo "🔢 Configurando versión de la imagen..."
          if [ "${{ env.BRANCH_NAME }}" = "master" ]; then
            IMAGE_NAME="baumanpeter/humberto:humbertobackend"
          else
            IMAGE_NAME="baumanpeter/humberto:humbertobackend-dev"
          fi
          IMAGE_VERSION="$IMAGE_NAME-v${{ github.run_number }}"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "✅ Imagen con versión: $IMAGE_VERSION"

      - name: Verify directory contents
        run: ls -l ./PH

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd PH
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      - name: Build Docker image and load locally
        run: |
          echo "🚀 Construyendo la imagen Docker para la rama ${{ env.BRANCH_NAME }} sin caché..."
          docker buildx build --platform linux/amd64 --no-cache --load -t $IMAGE_VERSION ./PH
          echo "✅ Imagen construida y cargada en Docker local."

      - name: List Docker images (debugging)
        run: docker images

      - name: Push Docker image to Docker Hub
        run: |
          echo "📤 Subiendo la imagen a Docker Hub..."
          docker push $IMAGE_VERSION
          echo "✅ Imagen subida exitosamente a Docker Hub para la rama ${{ env.BRANCH_NAME }}."