name: Desplegar Backend a Docker Hub y Servidor (Desarrollo)

on:
  push:
    branches:
      - dev  # Solo se ejecuta en push a dev
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Definir nombre de la imagen y versión (Dev)
        run: |
          IMAGE_NAME="baumanpeter/humberto:humbertobackend-dev"
          VERSION="v${{ github.run_number }}"
          IMAGE_VERSION="$IMAGE_NAME-$VERSION"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "✅ Imagen de desarrollo con versión: $IMAGE_VERSION"

      - name: Verificar contenido del directorio
        run: ls -l ./PH

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd PH
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      - name: Build Docker image and load locally
        run: |
          echo "🚀 Construyendo la imagen Docker de desarrollo..."
          docker buildx build --platform linux/amd64 --no-cache --load -t $IMAGE_VERSION ./PH
          echo "✅ Imagen de desarrollo construida y cargada localmente."

      - name: Push Docker image to Docker Hub
        run: |
          echo "📤 Subiendo la imagen a Docker Hub..."
          docker push $IMAGE_VERSION
          echo "✅ Imagen subida exitosamente."

      - name: Desplegar al servidor remoto (actualizando docker-compose de desarrollo)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST || secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER || secrets.SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY || secrets.SSH_KEY }}
          envs: IMAGE_VERSION
          script: |
            echo "📥 Iniciando despliegue remoto del backend (dev)..."
            docker pull $IMAGE_VERSION

            cd /root/Proyecto_H/DockerComposeHumberto-dev

            echo "🔄 Actualizando imagen en docker-compose.yml..."
            sed -i "s|baumanpeter/humberto:humbertobackend-dev-v[0-9]*|$IMAGE_VERSION|g" docker-compose.yml

            echo "🛠 Ejecutando script de actualización..."
            cd /root/Proyecto_H
            ./update_all_services.sh

            echo "🚀 Despliegue de desarrollo completado en el servidor."
