name: Deploy Backend to Docker Hub

on:
  push:
    branches:
      - master  # Solo se ejecuta en push a master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define Image Tag
        run: |
          IMAGE_NAME="baumanpeter/humberto:humbertobackend"
          IMAGE_VERSION="$IMAGE_NAME-v${{ github.run_number }}"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "✅ Imagen con versión: $IMAGE_VERSION"

      - name: Verify directory contents
        run: ls -l ./PH

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd PH
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      - name: Build Docker image and load locally
        run: |
          echo "🚀 Construyendo la imagen Docker..."
          docker buildx build --platform linux/amd64 --no-cache --load -t $IMAGE_VERSION ./PH
          echo "✅ Imagen construida y cargada en Docker local."

      - name: Push Docker image to Docker Hub
        run: |
          echo "📤 Subiendo la imagen a Docker Hub..."
          docker push $IMAGE_VERSION
          echo "✅ Imagen subida exitosamente."

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "📥 Iniciando despliegue remoto..."
            docker pull $IMAGE_VERSION
            docker stop humbertobackend || true
            docker rm humbertobackend || true
            docker run -d --name humbertobackend -p 8080:8080 $IMAGE_VERSION
            echo "🚀 Despliegue completado en el servidor."
