name: Deploy Backend to Docker Hub (Development)

on:
  push:
    branches:
      - dev  # Solo se ejecuta en push a dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Define Image Tag
        run: |
          IMAGE_NAME="baumanpeter/humberto:humbertobackend-dev"
          IMAGE_VERSION="$IMAGE_NAME-v${{ github.run_number }}"
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
          echo "✅ Imagen de desarrollo con versión: $IMAGE_VERSION"

      - name: Verify directory contents
        run: ls -l ./PH

      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd PH
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      - name: Build Docker image and load locally
        run: |
          echo "🚀 Construyendo la imagen Docker de desarrollo..."
          docker buildx build --platform linux/amd64 --no-cache --load -t ${{ env.IMAGE_VERSION }} ./PH
          echo "✅ Imagen de desarrollo construida y cargada en Docker local."

      - name: Push Docker image to Docker Hub
        run: |
          echo "📤 Subiendo la imagen de desarrollo a Docker Hub..."
          docker push ${{ env.IMAGE_VERSION }}
          echo "✅ Imagen de desarrollo subida exitosamente."

      - name: Deploy to Dev Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST || secrets.SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER || secrets.SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY || secrets.SSH_KEY }}
          envs: IMAGE_VERSION
          script: |
            echo "📥 Iniciando despliegue remoto en ambiente de desarrollo..."
            docker pull ${{ env.IMAGE_VERSION }}
            
            cd /root/Proyecto_H/DockerComposeHumberto-dev  # Directorio del servidor
            
            # Actualizar la versión en el docker-compose.yml
            sed -i "s|baumanpeter/humberto:humbertobackend-dev-v[0-9]*|${{ env.IMAGE_VERSION }}|g" docker-compose.yml
            
            # Ejecutar el script de actualización
            cd /root/Proyecto_H
            ./update_all_services.sh
            
            echo "🚀 Despliegue de desarrollo completado en el servidor."